all: 
	g++ -std=c++14 -Wall -Werror -Wno-unused-variable -Wno-unused-but-set-variable -o myfind myfind.c
	g++ -std=c++14 -Wall -Werror -Wno-unused-variable -Wno-unused-but-set-variable -o myfindplus myfind.cpp
clean:
	rm -f myfind myfindplus
